### 1.延迟调用defer
- defer特性
    1. 关键字 defer 用于注册延迟调用。
    2. 这些调用直到 return 前才被执。因此，可以用来做资源清理。
    3. 多个defer语句，按先进后出的方式执行。
    4. defer语句中的变量，在defer声明时就决定了。
    
- defer用于
    1. 关闭文件句柄
    2. 锁资源释放
    3. 数据库连接释放
    
- go 语言的defer功能强大，对于资源管理非常方便，但是如果没用好，也会有陷阱。
- defer 是先进后出，面的语句会依赖前面的资源，因此如果先前面的资源先释放了，后面的语句就没法执行了。

### 2.defer例子
```go
package main

import "fmt"

func main(){
	var whatever [5] struct{}

	for i := range whatever{
		// 运行结果
		// 4 3 2 1 0
		defer fmt.Println(i)
	}
}
```

### 3.defer碰上闭包
```go
package main

import "fmt"

func main()  {
	var whatever [5] struct{}
	for i := range whatever{
		// 执行结果
		// 4 4 4 4 4
		// 也就是说函数正常执行,由于闭包用到的变量 i 在执行的时候已经变成4,所以输出全都是4.也就是说函数正常执行,
		// 由于闭包用到的变量 i 在执行的时候已经变成4,所以输出全都是4.
		defer func() {fmt.Println(i)}()
	}
}
```

### 4.defer f.Close
```go
package main

import "fmt"

type Test struct {
	name string
}

func (t *Test) Close(){
	fmt.Println(t.name, " closed")
}

func Close(t Test){
	t.Close()
}

func main() {
	ts := []Test{
		{"a"},
		{"b"},
		{"c"},
	}

	// a closed
	// b closed
	// c closed
	for _,t := range ts{
		defer Close(t)
	}
}
```
- or
```go
package main

import "fmt"

type Test struct {
	name string
}

func (t *Test) Close(){
	fmt.Println(t.name, " closed")
}


func main() {
	ts := []Test{
		{"a"},
		{"b"},
		{"c"},
	}

	// a closed
	// b closed
	// c closed
	for _,t := range ts{
		t2 := t
		defer t2.Close()
	}
}
```

### 5.多个 defer 注册，按 FILO 次序执行 ( 先进后出 )
- 哪怕函数或某个延迟调用发生错误，这些调用依旧会被执行。
```go
package main

func test(x int){
	defer println("a")
	defer println("b")

	defer func() {
		println(100 / x)	// div0一场没有捕获，会往外抛
	}()

	defer println("c")
}

func main(){
	/**
		c
		b
		a
		panic: runtime error: integer divide by zero
	*/
	test(0)
}

```

### 6.defer调用参数在注册时求值被复制。可用指针或闭包"延迟调用"
- 这个例子用了闭包
```go
package main

func test2(){
	x, y := 10, 20

	defer func(x1 int) {
		println(x1, y)		// 10 120
							// y闭包引用
	}(x)					// x被复制

	x += 10
	y += 100
	println("x=",x, " y=", y)	// x=20 y=120
}

func main()  {
	test2()
}
```

### 7.滥用defer可能导致性能问题,尤其时在一个"大循环里"
- 例如以下
```go
package main

import (
	"fmt"
	"sync"
	"time"
)

var lock sync.Mutex

func test3(){
	lock.Lock()
	lock.Unlock()
}

func test3defer()  {
	lock.Lock()
	lock.Unlock()
}

func main() {
	func(){
		t1 := time.Now()
		for i:=0; i<10000; i++{
			test3()
		}
		elapsed := time.Since(t1)
		fmt.Println("test3 elapsed: ", elapsed)       // 223.162µs

	}()

	func(){
		t1 := time.Now()
		for i:=0; i<10000; i++{
			test3defer()
		}
		elapsed := time.Since(t1)
		fmt.Println("test3defer elapsed: ", elapsed)    // 781.304µs

	}()
}
```

### 8.defer陷阱(defer与closure)
- 如果 defer 后面跟的不是一个 closure 最后执行的时候我们得到的并不是最新的值。
```go
package main

import (
	"errors"
	"fmt"
)

// defer与闭包
func foo(a, b int)(i int, err error){
	// 这里不是闭包
	//first defer err <nil>
	defer fmt.Printf("first defer err %v\n", err)

	// 这里虽然时闭包，但是提前传了err,所以err是nil
	//second defer err <nil>

	defer func(err error) {fmt.Printf("second defer err %v\n", err)}(err)

	// 这里是闭包，用了外层的error
	//third defer err divided by zero
	defer func() {fmt.Printf("third defer err %v\n", err)}()

	if b == 0{
		err = errors.New("divided by zero")
		return
	}
	i = a / b
	return
}

func main(){
	foo(2,0)
}
```

### 9.defer与return
```go
package main

import "fmt"

func bar()(i int){
	i = 0
	// 在有具名返回值的函数中（这里具名返回值为 i）
	// 执行 return 2 的时候实际上已经将 i 的值重新赋值为 2。所以defer closure 输出结果为 2 而不是 1。
	defer func() {
		fmt.Println(i)	//2
	}()
	return 2
}

func main()  {
	bar()
}
```
